SimpleGraphic.vcxproj
This is an attempt to remove the dependency on the Visual Studio 2019 redistributable.
=> Changing Release build to use /MT instead of /MD

engine/system/win/sys_console.cpp
This causes the background to clear to the proper background color immediately.
The new PathOfBuilding.exe launcher requires this change or the console window will appear white where text has not been written to it.
=> Invalidate the entire client area for the console edit control after creating it

engine/render/r_font.cpp
The previous text-mode reading had a problem where the extractable character count of a file opened in non-binary (text) mode is subject to the actual contents of the file due to newline translation and EOF characters, and can only be determined by actually scanning over the content.
GetLen yields the binary size of the file and thus tends to overallocate the buffer, leading to the actual read attempting to read more data than can actually be extracted. This puts the code at the mercy of what garbage the target string contains from the allocator and how much data could actually be read.
=> Read font info files incrementally

engine/system/win/sys_main.cpp
The Copy function previously put the copied text from Lua verbatim on the clipboard as `CF_TEXT` which if not annotated with a locale is assumed to be in the current "input locale".
This commit changes it to instead assume that it's either in UTF-8 (or ASCII, which is a subset of UTF-8), transcoding it to UTF-16LE for `CF_UNICODETEXT`.
This enables the ability for the Lua side to copy out UTF-8 text which it may have obtained from an external source like trade or another API.
A brief audit of the current Lua source code does not reveal any call site that should contain text in the local codepage as build XML is supposed to be UTF-8 and no file paths seem to be copied.
=> Assume clipboard text from PoB is UTF-8 or ASCII

engine/system/win/sys_main.cpp
This adds support to catch the `+`, `-` and `0` characters from the numpad. This allows me to catch them as keye events for this feature: 
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4355
I think a lot of people expect those keys to work for zooming functionality, thus this PR.
Similar functionality can be tested i.e. in Chrome for zooming in / out and resetting.
=> Add key event support for VK_ADD, VK_SUBTRACT, VK_NUMPAD0

engine/system/win/sys_console.cpp
If the console errored out, pressing X would do nothing.  Easy way to test this was to run a second instance of PoB when the debug code was listening on a port:
```lua
local dbg = require('emmy_core')
dbg.tcpListen('localhost', 9966)
```
=> Close errored console on pressing X

ui_subscript.cpp
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5916
The reason people were able to get around this issue on the dev branch was because while we didn't load environment variables when starting PoB, we'd still load them when running subscripts.  In this case, the UpdateCheck was still loading the wrong Lua version from Scoop.
=> Fix Lua library loading from system environment variable

CMakeLists.txt, dep/stb/stb_image_resize.h, engine/core/core_image.cpp, engine/system/win/sys_video.cpp
The main window currently has a default icon as that logic wasn't ported over from the Win32 implementation.
This change reaches into the executable module on Windows and extracts the first icon group it finds in the resources and generates a set of icons suitable for application title bar use and applies them when the window has been created.
=> Obtain and set window icon from host executable

engine/render/r_font.cpp, engine/render/r_main.cpp, engine/render/r_main.h, libs/LZip/lzip.cpp, ui_main.cpp, ui_subscript.cpp
This set of changes makes the project build on macOS and addresses `new[]`/`delete` mismatches in LZip and fixes a double-free crash in subscripts when they encounter a fatal error, like when failing to load `lcurl.safe`.
=> Misc. macOS portability fixes

.gitmodules, CMakeLists.txt, engine/core/core_image.cpp, engine/core/core_video.cpp, engine/render.h, engine/render/r_font.cpp, engine/render/r_main.cpp, engine/render/r_main.h, engine/system/sys_video.h, engine/system/win/sys_video.cpp, ui_api.cpp, ui_main.cpp, ui_main.h
This PR supersedes my PRs #40, #41 and #42 for fixing the window positioning logic, adding the DPI awareness feature flag and addressing some problems around zlib usage.
It also reintroduces screenshot functionality, changes how the render queue is represented to a more efficient storage layout and adds boilerplate macros to wrap the functions exposed to Lua in a manner that allows C++ RAII usage inside the handlers as long as `LAssert` is replaced by `LExpect` which unwinds the C++ stack correctly.
The API changes between Lua and C++ are additive, no changes are needed on the Lua side apart from documenting the new flags and augment the headless wrapper when they start being used. This PR notably doesn't include the "Mesh" and "At" family of draw commands as they are not set in stone …
=> Evolve renderer backend and API surface

engine/render/r_main.cpp
We emulate DPI scaling by drawing to a smaller render target and scale it up with bilinear filtering to the desired DPI scale factor configured in the OS.
Windows seems to do crisper point filtering (nearest neighbour) for scale factors that are multiples of 100%.
This commit alters our behaviour to select the filter mode based on the DPI scale factor, opting for point filtering for non-fractional scaling.
=> fix: point-filter window for even DPI factors

engine/system/sys_main.h, engine/system/win/sys_main.cpp, ui_api.cpp
The user path location may both be inaccessible thanks to malfunctioning cloud providers and due to not being representable in the user codepage that is needed for interacting with the file system in a narrow way in Lua.
If an error occurs, the Lua function returns nil and an approximation in the user codepage of the path, suitable for use in an error message.
=> fix: harden UserPath against unusable folders

engine/core/core_video.cpp, engine/system/win/sys_video.cpp
The stored `vid_last` window size in Launch.cfg (or SimpleGraphic.cfg) can have a zero window width/height recorded; this typically due to closing the program while minimized.
As we have a minimum window size enforced in general, adapt the config loading to clamp the size to the minimum size and safeguard against the erroneous size and position being stored in the first place.
=> fix: clamp saved window size to minimum size

engine/system/win/sys_main.cpp
As we moved from WinAPI `FindFirstFile` to `std::filesystem` path tests and globbing was accidentally made case-sensitive as we use direct string comparison or regular expressions to match files.
We now always construct a regular expression for the glob and make the regex match case-insensitive. The regex is rebuilt on every file test but as the set of files is likely to be small this is of low impact; caching the regex in the search object would spread RE2 into the header.
=> fix: make file searches case-insensitive

engine/system/win/sys_local.h, engine/system/win/sys_main.cpp, engine/system/win/sys_video.cpp
When window is minimized, save resources and do not render anything
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7450
=> Do not render anything when window is minimized

LICENSE
SimpleGraphic 2.0 draws in many new dependencies. Most of them require us to reproduce the licence text in any and all distributions of the compiled artefacts to be legally able to distribute and use them.
=> Include licences of new third-party dependencies

ui_api.cpp
`remove` returns true if the deletion was successful, so we should be checking the inverse of the return value for errors.
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7508
=> Properly handle returned value for RemoveDir

engine/system/win/sys_main.cpp
Due to an unfortunate mixup of `resize()` vs. `reserve()` for the buffer containing the generated regex pattern for matching exact file paths, the buffer had garbage at the start leading to file searches not finding files if no wildcards were in effect.
=> fix: drop leading garbage from exact glob pattern

.github/workflows/main.yml, CMakeLists.txt, vcpkg-configuration.json
Most versions are trivial mostly revising the underlying node version required. Artifact uploading is changed significantly but not in any way that affect us.
chore: update vcpkg to master (2024-07-11)
Update vcpkg and the matching registry override to master as previous instabilities seem to have been addressed by now. 2024.06.15 isn't good enough as Abseil fails to build there.
fix: omit debug DLLs for release-only triplet
When building in CI with a `x64-windows-release` triplet to cut down on binary cache size and build times, the logic in the CMake script needs to not search for debug DLLs as no such files exist.
(cherry picked from commit c1ed5b6afb5de41addac75a5e382e8a7221ed864)
=> ci: update all actions to current, update vcpkg

vcpkg-configuration.json, vcpkg-ports/ports/glfw3/3.4_1/glfw-3.4_disable_dinput8.patch, vcpkg-ports/ports/glfw3/3.4_1/portfile.cmake, vcpkg-ports/ports/glfw3/3.4_1/vcpkg.json, vcpkg-ports/versions/baseline.json, vcpkg-ports/versions/g-/glfw3.json
Some HID devices block DirectInput8 device enumeration for many seconds which adversely affects software that uses GLFW without needing joysticks at all.
This change vendors the a port for GLFW with a patch to not load the `dinput8` library and thus disables all functionality that checks for its availability.
=> fix: disable glfw dinput8 joysticks

engine/render/r_main.cpp
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7534
In some environments POB may not have the permissions to create a new folder. This causes the current call to create_directory to throw an exception, which is not handled, causing a crash. This commit implements a basic check for error code of create_directory with an appropriate log message.
=> Add basic error checking to create_directory in `r_renderer_c::DoScreenshot` to prevent crash

ui_api.cpp, ui_main.cpp
Following discussion regarding https://github.com/PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic/pull/64 on discord it had been suggested that it may be beneficial to handle the screenshot hotkey from lua.
This pr adds a new function available from lua, `TakeScreenshot`, which allows for taking screenshots using the existing SimpleGraphic screenshot code. The hotkey to call the functionality directly inside of SG was removed as it was considered redundant.
=> Expose sceenshot funcitonality to lua. Remove screenshot hotkey.

ui_api.cpp
Current implementation of RemoveDir does not allow for removal of directories with content. This commit adds a recursive boolean parameter to RemoveDir allowing for recursive removal of directories and their contents.
See https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8197 for more discussion and potential use case.
=> Expose std::filesystem::remove_all functionality to lua side as an argument for RemoveDir

engine/system/sys_main.h, engine/system/win/sys_local.h, engine/system/win/sys_macos.mm, engine/system/win/sys_main.cpp, engine/system/win/sys_video.cpp, ui_api.cpp
ShellExecute on Wine can crash if you feed it a too long URL and some browsers have been documented to have a fairly low max limit of 2083 characters.
This rejects URLs that are longer than 2048 characters.
=> fix: refuse to open overly long URLs

engine/system/sys_video.h, engine/system/win/sys_video.cpp, ui_api.cpp
This PR allows Lua to set PoB as the active window for things like the final step of the OAuth flow.  As far as I can tell, Windows just flashes the taskbar icon, which should be sufficient for this purpose.
This also removes a redundant function that had the same functionality.
=> Expose SetForeground function to Lua API

.gitmodules, CMakeLists.txt, engine/render/r_main.cpp, engine/render/r_main.h, engine/render/r_texture.cpp
While ANGLE itself runs on legacy feature levels (10.0, 10.1); support for 11.0+ texture formats like BC7 is absent.
To support this lower end of GPUs we introduce fallback logic to transcode BC7 into RGBA with a hardcoded option to also reduce texture resolution by one level to counteract the 4x increase in VRAM usage this entails.
This adds a dependency on `cmp_core` from GPUOpen's Compressonator, built as a static library so there's no runtime deployment concerns.
=> feat: add BC7 CPU decode for legacy GPUs

.gitmodules, CMakeLists.txt
Homepage is here: https://lunarmodules.github.io/luasocket/index.html
One caveat to this PR is that I don't have a working Unix VM to see how to compile it there.  Not sure that's a blocker, but I know @zao was trying that out for a bit.
=> Add luasocket library for managing an internal server

vcpkg-configuration.json, vcpkg-ports/ports/gli/2021-07-06_3/bump-cmake-version.patch, vcpkg-ports/ports/gli/2021-07-06_3/disable-test.patch, vcpkg-ports/ports/gli/2021-07-06_3/portfile.cmake, vcpkg-ports/ports/gli/2021-07-06_3/vcpkg.json, vcpkg-ports/versions/baseline.json, vcpkg-ports/versions/g-/gli.json
CMake 4.0 removed previously deprecated backwards compatibility for CMake versions less than 3.5.
As the GitHub action runner for `windows-latest` now has CMake 4.0, our CI runs have started failing. To address this we vendor the `gli` port from upstream `vcpkg` with a patch to bump its minimum CMake requirement declared in the `gli` CMake scripts.
=> fix: vendor gli port for cmake 4.0 compatibility

engine/common/common.cpp, engine/system/sys_main.h, engine/system/win/sys_main.cpp, ui_api.cpp
This PR makes the three path query functions also expose an ACP encoding of the path if possible. The user path query can now also return a human-readable reason when it can't be obtained from the OS.
This is useful for scripts as they can now tell if paths can be expressed in the user's codepage.
This enables an use case in the update preparation logic where it can form absolute paths if the path is entirely within the ACP. When relative paths were in use there to work around that the path could be unspellable, the wrong directory could be operated on thanks to filesystem virtualisation.
=> Expose ACP versions of the base/script/user paths
